Log
darkleaf/di pull request #18
Opened 2024-10-16 17:17 UTC by darkleaf

2024-10-16 17:25 UTC, darkleaf commented on src/darkleaf/di/core.clj
> +(defn log [built-cb demolished-cb]
todo: docstring

2024-10-16 17:25 UTC, darkleaf commented on test/darkleaf/di/tutorial/x_log_test.clj
> +(ns darkleaf.di.tutorial.x-log-test
todo: проверить порядок выполнения registry-middleware, т.е. должен(может) ли быть лог первым, последним или посередине

2024-10-16 17:25 UTC, darkleaf commented on src/darkleaf/di/core.clj
> +              (built-cb key deps obj)
хз, нужно ли выдавать наружу объект, т.к. он может быть мутабельным.
Или раз это лог, то вообще делать `pr-str`? А то даже банально протестировать функи без приключений не получается.

```clojure
(pr-str a)
;; => "#function[darkleaf.di.tutorial.x-log-test/a]"
```

2024-10-16 17:25 UTC, darkleaf commented on src/darkleaf/di/core.clj
> +            (p/dependencies factory))
или вместо того, чтобы (built-cb key **deps** obj) лучше тут логировать несобранные зависимости, т.к. это просто данные

2024-10-16 17:25 UTC, darkleaf commented on src/darkleaf/di/core.clj
> +            (demolished-cb key obj)
логировать нужно после получается, и имена коллбеков должны быть в V3?

2024-10-16 17:25 UTC, darkleaf commented
@KGOH посмотри пожалуйста

2024-10-22 18:26 UTC, darkleaf commented on src/darkleaf/di/core.clj
> +            (p/dependencies factory))
p/dependencies вызывается несколько раз, и должен быть без сайд-эффектов

2024-10-23 12:07 UTC, KGOH requested changes

2024-10-23 12:07 UTC, KGOH commented on test/darkleaf/di/tutorial/x_log_test.clj
> +(ns darkleaf.di.tutorial.x-log-test
ссылочку добавить

2024-10-23 12:15 UTC, KGOH requested changes

2024-10-23 12:15 UTC, KGOH commented on src/darkleaf/di/core.clj
> +(defn log [built-cb demolished-cb]
"A logging middleware. Calls :after-build! and :after-demolish! during di/start. Must be the last one in the middleware chain.
Both callbacks are expected to accept the following arg {:keys [key obj]}."

2024-10-23 14:04 UTC, KGOH approved these changes

2024-10-23 14:08 UTC, merged